### ISSUE TITLE
How do I change nginx config settings for all / certain sites?

### ISSUE THREAD

**Issue by rogierborst** [johanvanhelden/dockerhero#26]
For some projects I'd like to be able to increase the file upload size or the max memory limit.

Is there an easy way to override the default settings on some or all sites?

I tried adding
```
http {
    client_max_body_size 50M;
}
```
to `custom.sample.conf`, but that seems to break dockerhero...

**Comment by johanvanhelden** [comment]
The best way to handle this at the moment is to make a copy of the default localtest.me vhost and edit some settings.

The default file can be found here: `https://github.com/johanvanhelden/dockerhero-nginx/blob/master/.conf/includes/localtest.me.conf`

Simply download this file, rename it to something that makes sense, for example: `big-uploads.localtest.me.conf`

Now place this file in Dockerhero's custom nginx config directory: `./dockerhero/nginx/conf/`

Now, you will need to modify the `server_name` into something else, because otherwise it will conflict with the default vhost.
Something like this will work, but it can be anything really: `server_name playground.big-uploads.localtest.me;`
You will need to do this for the both of them, in the port 80 block and the 443 block.

I've added a working example here:
https://gist.github.com/johanvanhelden/b243a0ea49819b1581feadeaeeb3bb5b

You can now upload files with large sizes (below is a 44MB PDF file):
![screenshot from 2018-09-16 14-40-35](https://user-images.githubusercontent.com/19389981/45596605-8d478700-b9be-11e8-80a3-06ee85794248.png)

**Comment by johanvanhelden** [comment]
But I think I might make the default upload size bigger by default. So you might want to hold off on manually making vhosts, if 64M would work for you.

**Comment by rogierborst** [comment]
I haven't had time to test it out, but I think I understand.
I was hoping for an easy way to globally override certain settings, but I guess I'll need to fully define vhosts for every project.

The new default of 64M certainly will help with my current problem. Thanks a bunch!
